terraform {
  required_version = ">= 1.0"
}

# Required application block for andasy
app "andasy" {
  version = "1.0.0"
  description = "Primary application settings"
  # add any additional configuration as needed
}

# Configure a simple provider (local is built-in, no configuration needed)
provider "local" {}

# Example resource using the local provider, this creates a file in the module directory
resource "local_file" "example" {
  content  = "This file was generated by andasy.hcl"
  filename = "${path.module}/andasy_output.txt"
}

# Example variable
variable "message" {
  description = "A custom message for Andasy"
  type        = string
  default     = "Hello from andasy.hcl!"
}

output "message_out" {
  value = var.message
}
